version: '3'
services:
  backend:
    image: naskio/strapi
    restart: always
    container_name: backend
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - type: bind
        source: backend
        target: /srv/app
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: frontend
        target: /app
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "900:80"
volumes:
  data:
  backend:
  frontend:
