import { postsApi } from '@features/posts'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ReactMarkdown from 'react-markdown'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { Box, Container } from '@mui/material'

export type PostProps = {
  id: string
}

export type PostParams = {
  id: string
}

const Post: NextPage<PostProps> = () => {
  const { query } = useRouter()
  const { id } = query as PostParams

  const { data, isFetching } = postsApi.useGetPostQuery(id)

  console.log(data, isFetching)

  return (
    <Container maxWidth="lg" sx={{ textAlign: 'center' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{data?.item.data.attributes.title}</h1>

        <Box sx={{ textAlign: 'left', overflow: 'hidden' }}>
          {data?.item.data.attributes.text && (
            <ReactMarkdown>{data?.item.data.attributes.text}</ReactMarkdown>
          )}
        </Box>
      </main>
    </Container>
  )
}

export default Post
